# Generated by Django 2.1.3 on 2018-12-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Usuario',
        ),
    ]
