# Generated by Django 2.1.3 on 2018-12-11 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20181210_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('data_publicacao', models.DateTimeField(default=datetime.datetime(2018, 12, 11, 0, 41, 17, 622650))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.Usuario')),
            ],
        ),
    ]
