# Generated by Django 2.1.3 on 2018-12-11 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_auto_20181211_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLogaado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 17, 18, 58, 467185)),
        ),
    ]
