# Generated by Django 2.1.3 on 2018-12-11 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_auto_20181211_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariologado',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contatos.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 17, 47, 18, 173022)),
        ),
    ]
