# Generated by Django 2.1.3 on 2018-12-11 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0008_auto_20181211_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=123, max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 18, 25, 53, 645870)),
        ),
        migrations.AlterField(
            model_name='usuariologado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.Usuario'),
        ),
    ]
