# Generated by Django 2.1.3 on 2018-12-11 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0009_auto_20181211_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='solicitante',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 18, 48, 8, 799128)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=15),
        ),
    ]
