# Generated by Django 2.1.3 on 2018-12-11 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_auto_20181211_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='solicitado',
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='contatos.Usuario'),
        ),
        migrations.AddField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='contatos.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 18, 52, 34, 393509)),
        ),
    ]
