# Generated by Django 2.1.3 on 2018-12-11 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0011_auto_20181211_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='contatos.Usuario'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='contatos.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 20, 13, 6, 646855)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(related_name='amigos_usuario', to='contatos.Usuario'),
        ),
    ]
