# Generated by Django 2.1.3 on 2018-12-11 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0012_auto_20181211_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 20, 17, 1, 818354)),
        ),
    ]
